version: 2.1

workflows:
  version: 2
  git-push:
    jobs:
      - dependencies

      - test-dev:
          requires:
            - dependencies
          filters:
            branches:
              ignore: master

      - deploy-dev:
          requires:
            - test-dev
          filters:
            branches:
              only: develop

      - test-pro:
          requires:
            - dependencies
          filters:
            branches:
              only: master

      - deploy-pro:
          requires:
            - test-pro
          filters:
            branches:
              only: master
executors:
  default:
    docker:
      - image: circleci/node:10.13.0-browsers

jobs:
  dependencies:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_cache
      - check_build_environment
      - run: npm install
      - save_node_cache

  test-dev:
    executor:
      name: default
    steps:
      - prepare_build
      - check_build_environment
      - run: npm run build-dev
      - save_workspace

  deploy-dev:
    executor:
      name: default
    steps:
      - restore_workspace
      - check_build_environment
      - run: npm run deploy-dev --token "$FIREBASE_TOKEN"

  test-pro:
    executor:
      name: default
    steps:
      - prepare_build
      - check_build_environment
      - run: npm run build-pro
      - save_workspace

  deploy-pro:
    executor:
      name: default
    steps:
      - restore_workspace
      - check_build_environment
      - run: npm run deploy-pro --token "$FIREBASE_TOKEN"

commands:
  check_build_environment:
    steps:
      - run:
          name: check build environment
          command: |
            node -v
            npm -v
            pwd
            find . -maxdepth 1 -type d | xargs ls -la

  # https://circleci.com/docs/ja/2.0/caching/#npm-node
  restore_node_cache:
    steps:
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

  save_node_cache:
    steps:
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

  prepare_build:
    steps:
      - checkout
      - restore_node_cache
      - run: npm install

  save_workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .

  restore_workspace:
    steps:
      - attach_workspace:
          at: .
